server:
  servlet:
    context-path: /lombok

spring:
  profiles:
    active: home
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb
