server:
  servlet:
    context-path: /student-management

spring:
  profiles:
    active: home

  jpa:
    show-sql: true
  mvc:
    view:
      prefix: /WEB-INF/views/
      suffix: .jsp

  web:
    resources:
      static-locations: /WEB-INF/static
